version: "3.8"
services:
  hadoop-master:
    image: jnamu/hadoop-cluster-node:latest
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
      - "7777:7777"
      - "9870:9870" # HDFS NameNode Web UI
      - "8020:8020" # HDFS NameNode HDFS API
      - "8088:8088" # YARN ResourceManager Web UI
      - "9000:9000" # fs.DefaultFS
    volumes:
      - hadoop-master-data:/opt/hadoop/data

  hadoop-worker-1:
    image: jnamu/hadoop-cluster-node:latest
    container_name: hadoop-worker-1
    hostname: hadoop-worker-1
    depends_on:
      - hadoop-master
    ports:
      - "8081:8081"
      - "9864:9864" # HDFS DataNode Web UI
      - "8042:8042" # YARN NodeManager Web UI
    volumes:
      - hadoop-master-data:/opt/hadoop/data

  hadoop-worker-2:
    image: jnamu/hadoop-cluster-node:latest
    container_name: hadoop-worker-2
    hostname: hadoop-worker-2
    depends_on:
      - hadoop-master
    ports:
      - "8082:8081"
      - "9865:9864" # HDFS DataNode Web UI
      - "8043:8042" # YARN NodeManager Web UI
    volumes:
      - hadoop-master-data:/opt/hadoop/data

volumes:
  hadoop-master-data:
  hadoop-slave1-data:
  hadoop-slave2-data: