version: '3.9'
services:
  master:
    container_name: master
    hostname: master
    image: jnamu/hadoop-master-v2:latest
    ports:
      - "8088:8088" # resourcemanager.webapp
      - "9870:9870" # dfs.namenode
      - "9000:9000"
      - "9864:9864"
      - "8042:8042"
    volumes:
      - m1:/usr/local/hadoop/data
  slave1:
    container_name: slave1
    hostname: slave1
    image: jnamu/hadoop-slave-v2:latest
    ports:
      - "9865:9864"
      - "8043:8042"
#        #      - "19888:19888" # mapreduce.jobhistory.webapp
#        #      - "8480:8480" # dfs.journalnode
#      #      - "9000:9000"
#      #      - "50010:50010"
    volumes:
      - s1:/usr/local/hadoop/data
  slave2:
    container_name: slave2
    hostname: slave2
    image: jnamu/hadoop-slave-v2:latest
    ports:
      - "9866:9864"
      - "8044:8042"
    volumes:
      - s2:/usr/local/hadoop/data
volumes:
  m1:
    external: true
  s1:
    external: true
  s2:
    external: true




