core-site:
  fs.defaultFS: hdfs://namenode:9000
  hadoop.tmp.dir: /hadoop/tmp
  io.file.buffer.size: 131072

hdfs-site:
  dfs.replication: 2
  dfs.blocksize: 134217728  # 128 MB
  dfs.namenode.name.dir: /hadoop/dfs/name

mapred-site:
  mapreduce.framework.name: yarn
  mapreduce.jobhistory.address: namenode:10020
  mapreduce.task.io.sort.mb: 256

yarn-site:
  yarn.resourcemanager.address: namenode:8032
  yarn.nodemanager.resource.memory-mb: 8192
  yarn.scheduler.minimum-allocation-mb: 1024