version: "3.8"

services:
  spark-master:
    container_name: spark-master
    image: jnamu/spark-node:latest
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
      - "7777:7777"
    command: ["/usr/local/spark/sbin/start-master.sh"]
  spark-worker-1:
    container_name: spark-worker-1
    image: jnamu/spark-node:latest
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: ["/usr/local/spark/sbin/start-worker.sh", "spark-master:7077"]
  spark-worker-2:
    container_name: spark-worker-2
    image: jnamu/spark-node:latest
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    command: ["/usr/local/spark/sbin/start-worker.sh", "spark-master:7077"]
